#define UID(x)		(getplayeruid (_this select x))
#define P_NAME(x) 	(name (_this select x))
#define P_SIDE(x)	(side (_this select x))
#define MODEL(x)	(TypeOf (_this select x))
#define P_OWNER(x)	(owner(_this select x))
#define SEL(z,x)	(z select x)
