INV_Lizenzen =

[
["mayorlic",dmv,"Governors license",1000],
["boat",dmv,localize "STRS_license_boat",1500],
["fboat",dmv,"Ferry Captain License",2500],
["esul",atm5,"Fire Rescue Training",100],
["bus_license",truckshop,"Bus License",1000],
["truck",truckshop,localize "STRS_license_truck",5000],
["taxi",taxishop,"Taxi License",5000],
["car",BuildSUV,localize "STRS_license_car",2500],
["oilukp",Oil_1,"Processing Training",30000],
["Baker",Bakery,"Baker's license",10000],
["mafial",mafs,"Mafia invitation",350000],
//["cooker",vending2,"Meat Processing license",10000],
["cocaine ga1",gangarea1,"GA1 cocaine Drug processor's license",35000],
["lsd ga1",gangarea1,"GA1 LSD Drug processor's license",35000],
["heroin ga2",gangarea2,"GA2 Heroin Drug processor's license",35000],
["lsd ga2",gangarea2,"GA2 LSD Drug processor's license",35000],
["heroin ga3",gangarea3,"GA3 Heroin Drug processor's license",35000],
["marijuana ga3",gangarea3,"GA3 Marijuana Drug processor's license",35000],
["heroin ga4",gangarea4,"GA4 Heroin Drug processor's license",35000],
["marijuana ga4",gangarea4,"GA4 Marijuana Drug processor's license",35000],
["air",airshop,localize "STRS_license_air",35000],
//["air",airshop4,localize "STRS_license_air",35000],
["comair",airshop3,"Commerical Air License",10000],
["IRAlicense",IRAveh,"IRA Training",900000],
["civcartune",tuning1,"Civilian Legal Car Tuning License",50000],
["icartune",tuning2,"Illegal Car Tuning License",100000],
//["gunprobationpistol",Licenseflag2,"Probation pistol license",20000],
["Pistollicense",gundealer1,"Pistol license",30000],
["riflelicense",vending2,"Hunting License",50000],
["assassinlic",assassinshop,"Illegal Assassin Weapons Fee",150000],
//["engineer",terrorbox, "Bomb Training License",900000],
//["bomb",gundealer1,"FUll Auto Weapons Fee",200000],
["terrorvip",vipterrorbox,"Terrorist VIP License",800000],
["terror",terrorbox,"Illegal Terrorist License",800000],
["probator",fbiatm,localize "STRS_license_probator",10000],
["patrol_training",copbank,localize "STRS_license_coppatrol",50000],
//["patrol_training",copbankeast,localize "STRS_license_coppatrol",50000],
["patrol_training",atm4,localize "STRS_license_coppatrol",50000],
//["response_training",copbank,localize "STRS_license_copresponse",30000],
["sobr_training",copswat,localize "STRS_license_copswat",150000],
["cg_boat",copbank,"PD Patrol Boat Training",20000],
["piratelicense",pirategearbox,"Pirate Training",400000],
["Donator_licence",Donatebuy,"Tier 1 Donator License",300000],
["Donator_licence",Donatebuy,"Tier 2 Donator License",300000],
["Donator_licence",Donatebuy,"Tier 3 Donator License",300000],
["tierx",tierxweapons,"Tier-X License",1350000],
["air_support_training",copbank,localize "STRS_license_copairsupport",45000],
["pmclicense",pmcAI,"PMC License",400000],
["dirtymoneylicense",dirtymoney1,"Dirty Money Processing Training",1],
//["SWATair",ILG_SwatAirStore,"SWAT Air Support License",250000],
["glassblowt",glassblower,"Glassblowing Training",30000],
["diamondp",diamond_processing,"Diamond Processing Training",30000],
["hpairlic",hpairshop,"High Performance Aircraft License",200000],
["warvetbribe",warvetshop,"War Veteran Bribe",200000],
["cocaine ga5",gangarea5,"GA5 Cocaine Drug processor's License",35000],
["heroin ga5",gangarea5,"GA5 Heroin Drug processor's License",35000]
];

INV_LizenzOwner = [];
