_role = player;

//action1a = _role addaction ["test","test.sqf",[1],1,false,true,"",""];
action6 = _role addaction ["Confiscate Money","mafiasafe.sqf", ["ausrauben", mafiasafe, "mafiasafe"],1,false,true,"","iscop and player distance mafiasafe <= 2"];
//=======================   ADMIN CAMERA ==============================================
action12 = _role addaction ["Admin Spectate","tcgcode.sqf",[1],1,false,true,"","player distance rubblepile <= 3"];
//action12a = _role addaction ["AntiClown","servermissionfile\umad.sqf";,[1],1,false,true,"","player distance rubblepile <= 3"];
//=====================================Elevator==============================================
action13 = _role addaction ["Up Elevator","elevator.sqf",[1],1,false,true,"",'player distance getmarkerpos "elevator1" <= 5'];
action13a = _role addaction ["Down Elevator","elevator.sqf",[2],1,false,true,"",'player distance elevator2 <= 5'];
//===================================== ASSASSINATION =================================================
action14 = _role addaction ["Escort VIP", "noscript.sqf", "[VIPtarget] join (group player); player groupchat ""escort the VIP to the police base before he is assassinated!"";",1,false,true,"","player distance VIPtarget < 5 and iscop"];
//===================================== TARGET RESET ==================================================
action17 = _role addaction ["Reset Targets","noscript.sqf",'{_x animate["terc",0]} foreach (nearestobjects [getpos player, ["TargetEpopup"],  500])',1,true,true,"",'player distance targetrange1 < 10'];
action18 = _role addaction ["Reset targets","noscript.sqf",'{_x animate["terc",0]} foreach (nearestobjects [getpos player, ["TargetEpopup"],  500])',1,true,true,"",'player distance targetrange2 < 10'];
//===================================== IMPOUND AREA==================================================
aImpound_1 = _role addaction ["Impound Lot","maindialogs.sqf",["impound"],1,false,true,"","player distance copcar <= 10"];
aImpound_2 = _role addaction ["Impound Lot","maindialogs.sqf",["impound"],1,false,true,"","player distance copcar1 <= 10"];
aImpound_3 = _role addaction ["Impound Lot","maindialogs.sqf",["impound"],1,false,true,"","player distance copswatcars <= 10"];
aImpound_4 = _role addaction ["Impound Lot","maindialogs.sqf",["impound"],1,false,true,"","player distance copfbicars <= 10"];
aImpound_5 = _role addaction ["Impound Lot(Aviation)","maindialogs.sqf",["impound"],1,false,true,"","player distance copair <= 5"];
//================================== COP DELETE EVIDENCE ================================================
action21 = _role addaction ["Take Criminal Weapons","noscript.sqf",'player groupchat "Evidence removed."; {deletevehicle _x} foreach (nearestobjects [getpos player, ["weaponholder"], 3])',1,true,true,"",'_weps = (nearestobjects [getpos player, ["weaponholder"], 3] select 0); player distance _weps < 5 and iscop'];
copremmoney = _role addaction ["Confiscate Illegal Money","noscript.sqf",'player groupchat "Money removed."; {deletevehicle _x} foreach (nearestobjects [getpos player, ["EvMoney"], 3])',1,true,true,"",'_weps = (nearestobjects [getpos player, ["EvMoney"], 3] select 0); player distance _weps < 5 and iscop'];
//suitcaseaction = _role addaction ["Confiscate evidence","noscript.sqf",'player groupchat "Evidence removed."; {deletevehicle _x} foreach (nearestobjects [getpos player, ["weaponholder"], 3])',1,true,true,"",'_weps = (nearestobjects [getpos player, ["weaponholder"], 3] select 0); player distance _weps < 5 and iscop'];
//================================== COP SLAVE ACTIONS ================================================
//action24 = _role addaction ["Who do you work for","noscript.sqf",'player groupchat format["this slave works for %1.", leader (nearestobjects [getpos player, civslavearray,  3] select 0)]',1,true,true,"",'_slave = (nearestobjects [getpos player, civslavearray, 3] select 0); !(_slave in playerarray) and player distance _slave < 5 and (leader _slave) in playerarray and iscop'];
//action25 = _role addaction ["Set slave free","noscript.sqf",'_slave = (nearestobjects [getpos player, civslavearray,  3] select 0); _civ = leader _slave; deletevehicle _slave; (format ["[""slave"", %1] spawn Isse_AddCrimeLogEntry; if(!(""being a slaver"" in %1_reason))then{%1_reason = %1_reason + [""being a slaver""]}; %1_wanted = 1; kopfMishy_%1 = kopfMishy_%1 + 20000;", _civ]) call broadcast;player groupchat "the slave has been freed!";',1,true,true,"",'_slave = (nearestobjects [getpos player, civslavearray, 3] select 0); !(_slave in playerarray) and player distance _slave < 5 and (leader _slave) in playerarray and iscop'];
//==================================== OBJECT ACTIONS =================================================

action_Juan_1 = _role addaction ["Move Object","noscript.sqf",'[] call Juan_Move_obj;',1,true,true,"",'_NearestObj = nearestobjects [getpos player,ILG_Moveable_Objects,10]; (!isNil "_NearestObj") && (count(_NearestObj) != 0) && (player distance (_NearestObj select 0)) < 5))'];
action22 = _role addaction ["Take Scuba Gear","noscript.sqf",'if (((call INV_GetOwnWeight) + ("gnt_scubaw" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["gnt_scubaw"],  10] select 0);["gnt_scubaw", 1] call INV_AddInvItem;player groupchat "you picked up scuba gear";',1,true,true,"",'player distance (nearestobjects [getpos player, ["gnt_scubaw"],  10] select 0) < 5'];
action23 = _role addaction ["Remove Spike Strip","noscript.sqf",'if (((call INV_GetOwnWeight) + ("spikestrip" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["spikestrip"],  10] select 0);["spikestrip", 1] call INV_AddInvItem;player groupchat "you picked up a spike strip";',1,true,true,"",'iscop and player distance (nearestobjects [getpos player, ["spikestrip"],  10] select 0) < 7'];
action24 = _role addaction ["Remove Stop Sign","noscript.sqf",'if (((call INV_GetOwnWeight) + ("glt_roadsign_octagon" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["glt_roadsign_octagon"],  10] select 0);["glt_roadsign_octagon", 1] call INV_AddInvItem;player groupchat "you picked up a stop sign";',1,true,true,"",'iscop and player distance (nearestobjects [getpos player, ["glt_roadsign_octagon"],  10] select 0) < 7'];
action24a = _role addaction ["Remove Concrete Barrier Short","noscript.sqf",'if (((call INV_GetOwnWeight) + ("il_barrier" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["il_barrier"],  10] select 0);["il_barrier", 1] call INV_AddInvItem;player groupchat "You picked up a Concrete Barrier Short";',1,true,true,"",'iscop and player distance (nearestobjects [getpos player, ["il_barrier"],  10] select 0) < 7'];
action25 = _role addaction ["Remove Searchlight","noscript.sqf",'if (((call INV_GetOwnWeight) + ("SearchLight_UN_EP1" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["SearchLight_UN_EP1"], 3] select 0);["SearchLight_UN_EP1", 1] call INV_AddInvItem;player groupchat "you picked up a searchlight";',1,true,true,"",'_light = (nearestobjects [getpos player, ["SearchLight_UN_EP1"],  3] select 0); !(_light in speedcamarray) and player distance _light < 5 and iscop'];
action26 = _role addaction ["Remove Roadblock","noscript.sqf",'if (((call INV_GetOwnWeight) + ("roadblock" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Land_CncBlock_Stripes"],  3] select 0);["roadblock", 1] call INV_AddInvItem;player groupchat "you picked up a roadblock";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Land_CncBlock_Stripes"],  3] select 0) < 5 and iscop'];
action27 = _role addaction ["Remove Bargate","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Bargate" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0);["Bargate", 1] call INV_AddInvItem;player groupchat "you picked up a bargate";',1,true,true,"",'iscop and player distance (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0) < 7'];
action28 = _role addaction ["Remove Road Cone","noscript.sqf",'if (((call INV_GetOwnWeight) + ("roadcone" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Land_coneLight"],  3] select 0);["roadcone", 1] call INV_AddInvItem;player groupchat "you picked up a road cone";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Land_coneLight"],  3] select 0) < 5'];
action29 = _role addaction ["Open/close gate","noscript.sqf",'_gate = (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0); if(_gate animationPhase "bargate" == 1)then{_gate animate ["bargate", 0]}else{_gate animate ["bargate", 1]};',1,true,true,"",'player distance (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0) < 7 and iscop'];
action30 = _role addaction ["Open/close gate","noscript.sqf",'_gate = (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0); if(_gate animationPhase "bargate" == 1)then{_gate animate ["bargate", 0]}else{_gate animate ["bargate", 1]};',1,true,true,"",'player distance (nearestobjects [getpos player, ["ZavoraAnim"],  10] select 0) < 7 and isciv'];
action34 = _role addaction ["Remove Bunker (small)","noscript.sqf",'if (((call INV_GetOwnWeight) + ("bunkersmall" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Land_fortified_nest_small"],  3] select 0);["bunkersmall", 1] call INV_AddInvItem;player groupchat "you picked up a bunker (small)";',1,true,true,"",'iscop and player distance (nearestobjects [getpos player, ["Land_fortified_nest_small"],  3] select 0) < 5'];
action35 = _role addaction ["Remove Danger Sign","noscript.sqf",'if (((call INV_GetOwnWeight) + ("danger" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Sign_Danger"],  3] select 0);["danger", 1] call INV_AddInvItem;player groupchat "you picked up a danger sign";',1,true,true,"",'player distance (nearestobjects [getpos player, ["Sign_danger"],  3] select 0) < 5'];
//action36 = _role addaction ["Gather Evidence","invest.sqf",'',1,true,true,"",'player distance (nearestobjects [getpos player, ["body"],  3] select 0) < 2'];
action37 = _role addaction ["Remove ladder","noscript.sqf",'if (((call INV_GetOwnWeight) + ("land_ladder_half" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["land_ladder_half"],  3] select 0);["land_ladder_half", 1] call INV_AddInvItem;player groupchat "you picked up a ladder";',1,true,true,"",'iscop and player distance (nearestobjects [getpos player, ["land_ladder_half"],  3] select 0) < 5'];
action38 = _role addaction ["Remove Road Barrier","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Land_RedWhiteBarrier" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["Land_RedWhiteBarrier"],  3] select 0);["Land_RedWhiteBarrier", 1] call INV_AddInvItem;player groupchat "you picked up a road barrier";',1,true,true,"",'iscop and player distance (nearestobjects [getpos player, ["Land_RedWhiteBarrier"],  3] select 0) < 5'];
action39 = _role addaction ["Remove Road Barrier","noscript.sqf",'if (((call INV_GetOwnWeight) + ("Roadbarrier_long" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["RoadBarrier_long"],  3] select 0);["RoadBarrier_long", 1] call INV_AddInvItem;player groupchat "you picked up a road barrier";',1,true,true,"",'iscop and player distance (nearestobjects [getpos player, ["RoadBarrier_long"],  3] select 0) < 5'];
action40 = _role addaction ["Remove Road Barrier","noscript.sqf",'if (((call INV_GetOwnWeight) + ("RoadBarrier_light" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [getpos player, ["RoadBarrier_light"],  3] select 0);["RoadBarrier_light", 1] call INV_AddInvItem;player groupchat "you picked up a road barrier";',1,true,true,"",'iscop and player distance (nearestobjects [getpos player, ["RoadBarrier_light"],  3] select 0) < 5'];
action41 = _role addaction ["Restrain Cop","restraincop.sqf",[],1,true,true,"",'_coparrest = (nearestobjects [getpos player, ["tcg_police_officerk9","tcg_police_officer","FOX_US_SFMRW_OFFD","policeman","vilas_sira_sheriffoff","vilas_sira_policeman","VIL_ctl_policeman_rd","vilas_sira_swat_m416","VIL_ctl_policeman","KPFS_Policeman_vest_des","KPFS_Policeman_vest_des_cap"], 3] select 1); player == cop1 && !(_coparrest getVariable ["restrained", false])'];
action42 = _role addaction ["Put Cop in Car","preArrestcop.sqf",[],1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and (_vcl call Is_Player_Veh) and player == cop1'];
action43 = _role addaction ["Arrest Cop","arrestcop.sqf",[],1,true,true,"",'_coparrest = (nearestobjects [getpos player, ["tcg_police_officerk9","tcg_police_officer","FOX_US_SFMRW_OFFD","policeman","vilas_sira_sheriffoff","vilas_sira_policeman","VIL_ctl_policeman_rd","vilas_sira_swat_m416","VIL_ctl_policeman","KPFS_Policeman_vest_des","KPFS_Policeman_vest_des_cap"], 3] select 1); player == cop1 && !(isNil "_coparrest") && player distance prisonflag <= 75 '];
action44 = _role addaction ["Search Cop","searchcop.sqf",[],1,true,true,"",'_coparrest = (nearestobjects [getpos player, ["tcg_police_officerk9","tcg_police_officer","FOX_US_SFMRW_OFFD","policeman","vilas_sira_sheriffoff","vilas_sira_policeman","VIL_ctl_policeman_rd","vilas_sira_swat_m416","VIL_ctl_policeman","KPFS_Policeman_vest_des","KPFS_Policeman_vest_des_cap"], 3] select 1); player == cop1 && !(isNil "_coparrest")'];
action41b = _role addaction ["Release Cop","restraincop.sqf",[],1,true,true,"",'_coparrest = (nearestobjects [getpos player, ["tcg_police_officerk9","tcg_police_officer","FOX_US_SFMRW_OFFD","policeman","vilas_sira_sheriffoff","vilas_sira_policeman","VIL_ctl_policeman_rd","vilas_sira_swat_m416","VIL_ctl_policeman","KPFS_Policeman_vest_des","KPFS_Policeman_vest_des_cap"], 3] select 1); player == cop1 && (_coparrest getVariable ["restrained", false])'];
//================================== COP CHIEF ELECTION ===============================================
//action44 = _role addaction ["Elect a Chief","maindialogs.sqf",["chief"],1,false,true,"","player distance rathaus <= 3 and iscop"];
//==================================== MAYOR ELECTION =================================================
action45 = _role addaction ["Elect a Governor","maindialogs.sqf",["wahlen"],1,false,true,"","player distance rathaus <= 3"];
//===================================== BUY INSURANCE ===================================================
//action49 = _role addaction [format["Buy Bank Insurance ($%1)", ("bankversicherung" call INV_getitemBuyCost)],"noscript.sqf",'if("Mishy" call INV_GetItemAmount < ("bankversicherung" call INV_getitemBuyCost))exitwith{player groupchat "not enough money"};["Mishy", -("bankversicherung" call INV_getitemBuyCost)] call INV_AddInvItem;["bankversicherung", 1] call INV_AddInvItem;player groupchat format["you bought bank insurance for $%1", ("bankversicherung" call INV_getitemBuyCost)];',1,false,true,"","player distance bailflag <= 3"];
//======================================= CRIMELOG ====================================================
action50 = _role addaction ["Crime Log","maindialogs.sqf",["coplog"],1,false,true,"","player distance rathaus <= 3"];
action67 = _role addaction [format ["Buy K9 ($%1)", dog_cost],"copdog.sqf", ["buydog"],1,false,true,"","player distance dogspawn <= 5 and (player == Cop3)"];
//action68 = _role addaction [format ["Buy K9 ($%1)", dog_cost],"civdog.sqf", ["buydog"],1,false,true,"","player distance dogspawn1 <= 5"];
action69 = _role addaction ["Who do you work for?","noscript.sqf",'player groupchat format["this hooker works for %1.", leader (nearestobjects [getpos player, civworkerarray,  3] select 0)]',1,true,true,"",'_slave = (nearestobjects [getpos player, civworkerarray, 3] select 0); !(_slave in playerarray) and player distance _slave < 5 and (leader _slave) in playerarray and iscop'];
action70 = _role addaction ["Send hooker home","noscript.sqf",'_slave = (nearestobjects [getpos player, civworkerarray,  3] select 0); _civ = leader _slave; deletevehicle _slave; (format ["[""slave"", %1] spawn Isse_AddCrimeLogEntry; if(!(""being a pimp"" in %1_reason))then{%1_reason = %1_reason + [""being a pimp""]}; %1_wanted = 1; kopfMishy_%1 = kopfMishy_%1 + 20000;", _civ]) call broadcast;player groupchat "the hooker has been sent home!";',1,true,true,"",'_slave = (nearestobjects [getpos player, civworkerarray, 3] select 0); !(_slave in playerarray) and player distance _slave < 5 and (leader _slave) in playerarray and iscop'];
action78 = _role addaction ["Get in trailer","trucking.sqf",[4],1,true,true,"",'_vcl = (nearestobjects [getpos player, ["cl_del_mackr","cl_trucktest_mackr","cl_flatbed_mackr"], 5] select 0);player distance _vcl < 5 and (_vcl call Is_Player_Veh)'];
action79 = _role addaction ["Search trailer","trucking.sqf",[5],1,true,true,"",'_carg = (nearestobjects [getpos player, ["Land_bags_stack_EP1","Land_bags_EP1","Land_Bag_EP1"], 2] select 0);player distance _carg < 2 and iscop'];
//====================================== VEHICLE ACTIONS ================================================
action84 = _role addaction [localize "STRS_addaction_trunk_see","noscript.sqf",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);_str = format["%1_storage", _vcl];[_str] execVM "vehiclecheck.sqf";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and !(_vcl in INV_VehicleArray) and (_vcl call Is_Player_Veh) and iscop'];
action85 = _role addaction [localize "STRS_addaction_trunk_check","noscript.sqf",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);_str = format["%1_storage", _vcl];if([_vcl,_str] call INV_RemoveIllegalStorage)then{call compile format["publicvariable ""%1"";", _str]};',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and !(_vcl in INV_VehicleArray) and (_vcl call Is_Player_Veh) and iscop'];
action87 = _role addaction ["Pull out","noscript.sqf",'(nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0) execVM "pullout.sqf";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and count (crew _vcl) > 0 and (_vcl call Is_Player_Veh) and (call INV_isArmed)'];
action88 = _role addaction [localize "STRS_addAction_vehicleinfo","noscript.sqf",'(nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0) execVM "vehinfo.sqf";',1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and (_vcl call Is_Player_Veh)'];
action89 = _role addaction ["Put civilian in car","preArrest.sqf",[],1,true,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and (_vcl call Is_Player_Veh) and iscop'];
//======================================== SHOP EXPORT ==================================================
_num1 = (shop1 call INV_getshopnum);
_num2 = (shop2 call INV_getshopnum);
_num4 = (shop4 call INV_getshopnum);
_num5 = (pdfood call INV_getshopnum);
action98 = _role addaction ["Shop 1 export","shopdialogs.sqf",[_num1],1,false,true,"","player distance shop1export <= 3"];
action99 = _role addaction ["Shop 2 export","shopdialogs.sqf",[_num2],1,false,true,"","player distance shop2export <= 3"];
action102 = _role addaction ["Shop 4 export","shopdialogs.sqf",[_num4],1,false,true,"","player distance shop4export <= 3"];
action103 = _role addaction ["Food and Candy","shopdialogs.sqf",[_num5],1,false,true,"",'player distance (nearestobjects [getpos player, ["ibr_van_BNK"],  10] select 0) < 3'];
//========================   unflip vehicle     ================================
action121 = _role addaction ["Unflip vehicle","unflipvehicle.sqf",["unflip"],1,false,true,"",'_vcl = (nearestobjects [getpos player, ["Air", "Ship", "LandVehicle"], 3] select 0);player distance _vcl < 5 and (_vcl call Is_Player_Veh)'];
//=========================    Cop Patrol actions/BUS   ==============================
action122 = _role addaction ["Get patrol mission","coppatrol.sqf",["start"],1,false,true,"","iscop and (player distance copbank <= 4 or player distance atm4 <= 4) and !pmissionactive and !patrolwaittime"];
action123 = _role addaction ["Cancel patrol mission","coppatrol.sqf",["end"],1,false,true,"","iscop and pmissionactive and player distance copbank <= 4"];
action124 = _role addaction ["Get Security mission","coppatrol.sqf",["start1"],1,false,true,"","iscop and player distance copbank <= 4 and !pmissionactive1 and !patrolwaittime1"];
action125 = _role addaction ["Cancel Security mission","coppatrol.sqf",["end1"],1,false,true,"","iscop and pmissionactive1 and player distance copbank <= 4"];
action122 = _role addaction ["Get patrol mission","coppatrol.sqf",["start"],1,false,true,"","iscop and (player distance copbankeast <= 4 or player distance atm4 <= 4) and !pmissionactive and !patrolwaittime"];
action123 = _role addaction ["Cancel patrol mission","coppatrol.sqf",["end"],1,false,true,"","iscop and pmissionactive and player distance copbankeast <= 4"];
action124 = _role addaction ["Get Security mission","coppatrol.sqf",["start1"],1,false,true,"","iscop and player distance copbankeast <= 4 and !pmissionactive1 and !patrolwaittime1"];
action125 = _role addaction ["Cancel Security mission","coppatrol.sqf",["end1"],1,false,true,"","iscop and pmissionactive1 and player distance copbankeast <= 4"];

action125 = _role addaction ["Remove Speed Upgrade","Juan\Civs\SUremove.sqf",[""],1,false,true,"","player distance SUAI <= 3"];

actionillegalSU = _role addaction ["Remove Illegal Speed Upgrade","Steve\CopRemoveSU.sqf",[""],1,false,true,"",'_vcl = (nearestobjects [getpos player, ["LandVehicle"], 5] select 0);_Upgrades = _vcl getVariable "Tuning";player distance _vcl < 5 and !(isNil "_Upgrades")'];
//======================================== VICE SKIN CHANGING==========================================================
actionskinshop3cop = _role addaction ["Undercover Priest ($0)","noscript.sqf",'["Priest"] call clothes;',1,true,true,"",'player distance fbiskin < 10 and iscop && vehicle player in [cop19, cop20]'];
actionskinshop4cop = _role addaction ["Undercover Profiteer (Red) ($0)","noscript.sqf",'["Profiteer4"] call clothes;',1,true,true,"",'player distance fbiskin < 10 and iscop && vehicle player in [cop19, cop20]'];
actionskinshop5cop = _role addaction ["Undercover Citizen Green ($0)","noscript.sqf",'["Citizen4"] call clothes;',1,true,true,"",'player distance fbiskin < 10 and iscop && vehicle player in [cop19, cop20]'];
actionskinshop8cop = _role addaction ["Undercover Woodlander Camo ($0)","noscript.sqf",'["Woodlander3"] call clothes;',1,true,true,"",'player distance fbiskin < 10 and iscop && vehicle player in [cop19, cop20]'];
actionskinshop9cop = _role addaction ["Undercover Sketchy Surgeon ($0)","noscript.sqf",'["Dr_Hladik_EP1"] call clothes;',1,true,true,"",'player distance fbiskin < 10 and iscop && vehicle player in [cop19, cop20]'];
actionskinshop10cop = _role addaction ["Undercover Camo Pants ($0)","noscript.sqf",'["ibr_lingorman2"] call clothes;',1,true,true,"",'player distance fbiskin < 10 and iscop && vehicle player in [cop19, cop20]'];
actionskinshop11cop = _role addaction ["Undercover Trucker Orange ($0)","noscript.sqf",'["sah_civilian4_pants"] call clothes;',1,true,true,"",'player distance fbiskin < 10 and iscop && vehicle player in [cop19, cop20]'];
actionskinshop12cop = _role addaction ["Undercover Islander ($0)","noscript.sqf",'["sah_civilian2_pants"] call clothes;',1,true,true,"",'player distance fbiskin < 10 and iscop && vehicle player in [cop19, cop20]'];
//actionmil2cop = _role addaction ["Undercover IRA Rebel","noscript.sqf",'["INS_Soldier_2"] call clothes;',1,true,true,"",'player distance fbiskin < 5 and iscop && vehicle player in [cop19, cop20]'];
//=======================DHS Skins===================================================
actionDHS1 = _role addaction ["Advanced Patrol Skin (VIP)","noscript.sqf",'["VIL_ctl_policeman_rd"] call clothes;',1,true,true,"",'player distance copvip < 5 and iscop && (player in [Cop4,Cop5,Cop6,Cop7,Cop8,Cop9,Cop10,Cop11,Cop12,Cop13]) && ((((getPlayerUID player) in vipdonators2)||((getPlayerUID player) in superadmin)) || (call Tier2_Unlocked))'];
actionDHS2 = _role addaction ["Detective Skin (VIP)","noscript.sqf",'["KPFS_Policeman_vest_des"] call clothes;',1,true,true,"",'player distance copvip < 5 and iscop && ((((getPlayerUID player) in vipdonators2)||((getPlayerUID player) in superadmin)) || (call Tier2_Unlocked))'];
actionDHS3 = _role addaction ["Sheriff w/Hat (VIP)","noscript.sqf",'["vilas_sira_sheriffoff"] call clothes;',1,true,true,"",'player distance copvip < 5 and iscop && (player in [Cop14,Cop15,Cop16,Cop17,Cop18]) && ((((getPlayerUID player) in vipdonators2)||((getPlayerUID player) in superadmin)) || (call Tier2_Unlocked))'];
actionDHS4 = _role addaction ["Advanced Patrol Skin (VIP)","noscript.sqf",'["VIL_ctl_policeman_rd"] call clothes;',1,true,true,"",'player distance copvipbankeast < 5 and iscop && (player in [Cop4,Cop5,Cop6,Cop7,Cop8,Cop9,Cop10,Cop11,Cop12,Cop13]) && ((((getPlayerUID player) in vipdonators2)||((getPlayerUID player) in superadmin)) || (call Tier2_Unlocked))'];
actionDHS5 = _role addaction ["Detective Skin (VIP)","noscript.sqf",'["KPFS_Policeman_vest_des"] call clothes;',1,true,true,"",'player distance copvipbankeast < 5 and iscop && ((((getPlayerUID player) in vipdonators2)||((getPlayerUID player) in superadmin)) || (call Tier2_Unlocked))'];
actionDHS6 = _role addaction ["Sheriff w/Hat (VIP)","noscript.sqf",'["vilas_sira_sheriffoff"] call clothes;',1,true,true,"",'player distance copvipbankeast < 5 and iscop && (player in [Cop14,Cop15,Cop16,Cop17,Cop18]) && ((((getPlayerUID player) in vipdonators2)||((getPlayerUID player) in superadmin)) || (call Tier2_Unlocked))'];
actionDHS7 = _role addaction ["Advanced Patrol Skin (VIP)","noscript.sqf",'["VIL_ctl_policeman_rd"] call clothes;',1,true,true,"",'player distance copvipbanksheriff < 5 and iscop && (player in [Cop4,Cop5,Cop6,Cop7,Cop8,Cop9,Cop10,Cop11,Cop12,Cop13]) && ((((getPlayerUID player) in vipdonators2)||((getPlayerUID player) in superadmin)) || (call Tier2_Unlocked))'];
actionDHS8 = _role addaction ["Detective Skin (VIP)","noscript.sqf",'["KPFS_Policeman_vest_des"] call clothes;',1,true,true,"",'player distance copvipbanksheriff < 5 and iscop && ((((getPlayerUID player) in vipdonators2)||((getPlayerUID player) in superadmin)) || (call Tier2_Unlocked))'];
actionDHS9 = _role addaction ["Sheriff w/Hat (VIP)","noscript.sqf",'["vilas_sira_sheriffoff"] call clothes;',1,true,true,"",'player distance copvipbanksheriff < 5 and iscop && (player in [Cop14,Cop15,Cop16,Cop17,Cop18]) && ((((getPlayerUID player) in vipdonators2)||((getPlayerUID player) in superadmin)) || (call Tier2_Unlocked))'];

//action250 = _role addaction ["Open Jail Door","jaildoor.sqf",["open"],1,false,true,"",'(iscop) and (player distance jaild < 3) and (policehq animationPhase "jdoor" < 0.5)'];
//action251 = _role addaction ["Close Jail Door","jaildoor.sqf",["close"],1,false,true,"",'(iscop) and (player distance jaild < 3) and (policehq animationPhase "jdoor" >= 0.5)'];
//======================================== Donate shop===================================================

_num15 = (donatebuy call INV_getshopnum);
actiondonate = _role addaction ["Donator Shop","shopdialogs.sqf",[_num15],1,false,true,"","player distance donatebuy <= 5"];
_num16 = (ukgrecompense call INV_getshopnum);
action81 = _role addaction ["Chokehold","detain.sqf",'',1,true,true,"",'animationState ((nearestObjects [player, ["Man"], 3]) select 1) == ILG_Restrain_Anim && ((nearestObjects [player, ["Man"], 3]) select 1) in civarray'];
action83 = _role addaction ["Release","detach.sqf",'',1,true,true,"",'animationState ((nearestObjects [player, ["Man"], 3]) select 1) == ILG_Restrain_Anim && ((nearestObjects [player, ["Man"], 3]) select 1) in civarray'];
action295 = _role addaction ["<t color=""#00FF00"">" +"ILL Phone", "handy.sqf",[],1,false,true,"",'ILG_Phone_Action_Enable'];
actiondispatch = _role addaction ["Dispatch System","dispatchsys\dlgopen.sqf",'',1,false,true,"",'(player == cop2) and (player distance dispatchdesk <= 4)'];
actionBodyBag = _role addaction ["Check DNA","noscript.sqf",'[3] execVM "bodyBags.sqf";',1,true,true,"",'(player distance ((nearestObjects [player, ["BODY"], 3]) select 0)) < 3'];
ActionAirCop = _role addaction ["Switch to Air Unit","noscript.sqf",'[] call Switch_CopAirSkin;',1,true,true,"",'player distance copair < 5 and iscop'];
ActionAirCopRevert = _role addaction ["Take off Air Unit","noscript.sqf",'[] call Switch_FromCopAirSkin;',1,true,true,"",'player distance copair < 5 && iscop && ((typeOf player) == "US_Soldier_Pilot_EP1")'];
ActionAirCop2 = _role addaction ["Switch to Air Unit","noscript.sqf",'[] call Switch_CopAirSkin;',1,true,true,"",'player distance copair2 < 5 and iscop'];
ActionAirCopRevert2 = _role addaction ["Take off Air Unit","noscript.sqf",'[] call Switch_FromCopAirSkin;',1,true,true,"",'player distance copair2 < 5 && iscop && ((typeOf player) == "US_Soldier_Pilot_EP1")'];
ActionAirCop3 = _role addaction ["Switch to Air Unit","noscript.sqf",'[] call Switch_CopAirSkin;',1,true,true,"",'player distance copair3 < 5 and iscop'];
ActionAirCopRevert3 = _role addaction ["Take off Air Unit","noscript.sqf",'[] call Switch_FromCopAirSkin;',1,true,true,"",'player distance copair3 < 5 && iscop && ((typeOf player) == "US_Soldier_Pilot_EP1")'];
CopSpeedCam = _role addaction ["Take Speed","noscript.sqf",'[] call Juan_CopSpeedCam;',1,true,true,"",'iscop && ((currentWeapon player) == "Binocular_Vector")'];
//=======================SWAT Skins===================================================
SWATSkin1 = _role addaction ["Change to SWAT uniform.","noscript.sqf",'["vilas_sira_swat_m416"] call clothes;',1,true,true,"",'player distance swatatm < 5 and iscop && (player in [Cop21,Cop22,Cop23,Cop24,Cop25])'];
SWATSkin2 = _role addaction ["Change to Patrol uniform.","noscript.sqf",'["tcg_police_officer"] call clothes;',1,true,true,"",'player distance swatatm < 5 and iscop && (player in [Cop21,Cop22,Cop23,Cop24,Cop25])'];
//=======================EPD Skins===================================================
EPDSkin6 = _role addaction ["K9 Officer","noscript.sqf",'["epd_k9_officer"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin1 = _role addaction ["Police Officer (Vest)","noscript.sqf",'["epd_gd_vest_officer"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin2 = _role addaction ["Police Officer (Hat)","noscript.sqf",'["epd_officerhat"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin8 = _role addaction ["Police Officer (Rec.)","noscript.sqf",'["epd_gd_r"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin3 = _role addaction ["Police Officer (Cpl.)","noscript.sqf",'["epd_gd_cpl"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin4 = _role addaction ["Police Officer (Sgt.)","noscript.sqf",'["epd_gd_sgt"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin9 = _role addaction ["Police Officer (3rd Const.)","noscript.sqf",'["epd_gd_3c"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin5 = _role addaction ["Police Officer (2nd Const.)","noscript.sqf",'["epd_gd_2c"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin7 = _role addaction ["Police Officer (1st Const.)","noscript.sqf",'["epd_gd_1c"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin10 = _role addaction ["Police Officer (Lt.)","noscript.sqf",'["epd_gd_lt"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin11 = _role addaction ["Police Officer (Cpt.)","noscript.sqf",'["epd_gd_cpt"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin12 = _role addaction ["Police Officer (Com.)","noscript.sqf",'["epd_gd_com"] call clothes;',1,true,true,"",'player distance epdgeneralveh < 5 and iscop'];
EPDSkin13 = _role addaction ["Traffic Cop (Vest)","noscript.sqf",'["epd_tsu_vest_officer"] call clothes;',1,true,true,"",'player distance epdtrafficveh < 5 and iscop'];
EPDSkin15 = _role addaction ["Traffic Cop (Rec.)","noscript.sqf",'["epd_tsu_r"] call clothes;',1,true,true,"",'player distance epdtrafficveh < 5 and iscop'];
EPDSkin15 = _role addaction ["Traffic Cop (Cpl.)","noscript.sqf",'["epd_tsu_cpl"] call clothes;',1,true,true,"",'player distance epdtrafficveh < 5 and iscop'];
EPDSkin14 = _role addaction ["Traffic Cop (Sgt.) ","noscript.sqf",'["epd_tsu_sgt"] call clothes;',1,true,true,"",'player distance epdtrafficveh < 5 and iscop'];
EPDSkin15 = _role addaction ["Traffic Cop (3rd Const.)","noscript.sqf",'["epd_tsu_3c"] call clothes;',1,true,true,"",'player distance epdtrafficveh < 5 and iscop'];
EPDSkin15 = _role addaction ["Traffic Cop (2nd Const.)","noscript.sqf",'["epd_tsu_2c"] call clothes;',1,true,true,"",'player distance epdtrafficveh < 5 and iscop'];
//EPDSkin15 = _role addaction ["Traffic Cop (1st Const.)","noscript.sqf",'["epd_tsu_1c"] call clothes;',1,true,true,"",'player distance epdtrafficveh < 5 and iscop'];
EPDSkin15 = _role addaction ["Traffic Cop (Lt.)","noscript.sqf",'["epd_tsu_lt"] call clothes;',1,true,true,"",'player distance epdtrafficveh < 5 and iscop'];
EPDSkin15 = _role addaction ["Traffic Cop (Capt.)","noscript.sqf",'["epd_tsu_cpt"] call clothes;',1,true,true,"",'player distance epdtrafficveh < 5 and iscop'];
EPDSkin15 = _role addaction ["Emergency Response Team Leader","noscript.sqf",'["epd_ert_leader"] call clothes;',1,true,true,"",'player distance epdtrafficveh < 5 and iscop'];
EPDSkin15 = _role addaction ["ERT Officer","noscript.sqf",'["epd_ert"] call clothes;',1,true,true,"",'player distance epdtrafficveh < 5 and iscop'];

RequestBackup = _role addAction ["Request Backup", "noscript.sqf", '[] call Activate_Backup_Button', 5.9, false, true, "", 'iscop && ("ItemGPS" in (items player)) && Allow_Backup'];
PanicButton = _role addAction ["<t color=""#ff0000"">" +"PANIC BUTTON", "noscript.sqf", '[] call Activate_Panic_Button', 6, false, true, "", 'iscop && Allow_Panic && ("ItemGPS" in (items player))'];
