dispatch1 = player addaction ["Cop 1","noscript.sqf",'[cop1] execVM "dispatchsys\dispatch.sqf";',1,true,true,"",''];
dispatch2 = player addaction ["Cop 2","noscript.sqf",'[cop2] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch3 = player addaction ["Cop 3","noscript.sqf",'[cop3] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch4 = player addaction ["Cop 4","noscript.sqf",'[cop4] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch5 = player addaction ["Cop 5","noscript.sqf",'[cop5] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch6 = player addaction ["Cop 6","noscript.sqf",'[cop6] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch7 = player addaction ["Cop 7","noscript.sqf",'[cop7] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch8 = player addaction ["Cop 8","noscript.sqf",'[cop8] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch9 = player addaction ["Cop 9","noscript.sqf",'[cop9] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch10 = player addaction ["Cop 10","noscript.sqf",'[cop10] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch11 = player addaction ["Cop 11","noscript.sqf",'[cop11] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch12 = player addaction ["Cop 12","noscript.sqf",'[cop12] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch13 = player addaction ["Cop 13","noscript.sqf",'[cop13] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch14 = player addaction ["Cop 14","noscript.sqf",'[cop14] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch15 = player addaction ["Cop 15","noscript.sqf",'[cop15] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch16 = player addaction ["Cop 16","noscript.sqf",'[cop16] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch17 = player addaction ["Cop 17","noscript.sqf",'[cop17] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch18 = player addaction ["Cop 18","noscript.sqf",'[cop18] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch19 = player addaction ["Cop 19","noscript.sqf",'[cop19] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch20 = player addaction ["Cop 20","noscript.sqf",'[cop20] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch21 = player addaction ["Cop 21","noscript.sqf",'[cop21] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch22 = player addaction ["Cop 22","noscript.sqf",'[cop22] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch23 = player addaction ["Cop 23","noscript.sqf",'[cop23] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch24 = player addaction ["Cop 24","noscript.sqf",'[cop24] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
dispatch25 = player addaction ["Cop 25","noscript.sqf",'[cop25] execVM "dispatchsys\dispatch.sqf"',1,true,true,"",''];
if (alive cop1) then {player addAction dispatch1};
if (alive cop2) then {player addAction dispatch2};
if (alive cop3) then {player addAction dispatch3};
if (alive cop4) then {player addAction dispatch4};
if (alive cop5) then {player addAction dispatch5};
if (alive cop6) then {player addAction dispatch6};
if (alive cop7) then {player addAction dispatch7};
if (alive cop8) then {player addAction dispatch8};
if (alive cop9) then {player addAction dispatch9};
if (alive cop10) then {player addAction dispatch10};
if (alive cop11) then {player addAction dispatch11};
if (alive cop12) then {player addAction dispatch12};
if (alive cop13) then {player addAction dispatch13};
if (alive cop14) then {player addAction dispatch14};
if (alive cop15) then {player addAction dispatch15};
if (alive cop16) then {player addAction dispatch16};
if (alive cop17) then {player addAction dispatch17};
if (alive cop18) then {player addAction dispatch18};
if (alive cop19) then {player addAction dispatch19};
if (alive cop20) then {player addAction dispatch20};
if (alive cop21) then {player addAction dispatch21};
if (alive cop22) then {player addAction dispatch22};
if (alive cop23) then {player addAction dispatch23};
if (alive cop24) then {player addAction dispatch24};
if (alive cop25) then {player addAction dispatch25};
